{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "1841a1c1-0e8a-4f9d-b1d6-54da18b3d3bd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Total records: 54041\n"
     ]
    }
   ],
   "source": [
    "import dask.dataframe as dd\n",
    "\n",
    "# Load the consolidated Parquet dataset\n",
    "df = dd.read_parquet(\"parquet_database\")\n",
    "\n",
    "# Count total records\n",
    "total_records = len(df)\n",
    "print(f\"Total records: {total_records}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "9b063edb-66fd-4166-96d1-ee204be9bd54",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.12/site-packages (1.26.4)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (1.13.1)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install numpy scipy\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "b8810c4a-dbc5-42f7-b986-4dc12ca3e48f",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting dask-ml\n",
      "  Using cached dask_ml-2024.4.4-py3-none-any.whl.metadata (5.9 kB)\n",
      "Collecting dask-glm>=0.2.0 (from dask-ml)\n",
      "  Using cached dask_glm-0.3.2-py2.py3-none-any.whl.metadata (1.5 kB)\n",
      "Requirement already satisfied: dask>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[array,dataframe]>=2.4.0->dask-ml) (2024.8.2)\n",
      "Requirement already satisfied: distributed>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (2024.8.2)\n",
      "Requirement already satisfied: multipledispatch>=0.4.9 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (0.6.0)\n",
      "Requirement already satisfied: numba>=0.51.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (0.60.0)\n",
      "Requirement already satisfied: numpy>=1.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.26.4)\n",
      "Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (24.1)\n",
      "Requirement already satisfied: pandas>=0.24.2 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (2.2.2)\n",
      "Requirement already satisfied: scikit-learn>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.5.1)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.13.1)\n",
      "Requirement already satisfied: click>=8.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (8.1.7)\n",
      "Requirement already satisfied: cloudpickle>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (3.0.0)\n",
      "Requirement already satisfied: fsspec>=2021.09.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (2024.6.1)\n",
      "Requirement already satisfied: partd>=1.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (1.4.1)\n",
      "Requirement already satisfied: pyyaml>=5.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (6.0.1)\n",
      "Requirement already satisfied: toolz>=0.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml) (0.12.0)\n",
      "Collecting sparse>=0.7.0 (from dask-glm>=0.2.0->dask-ml)\n",
      "  Downloading sparse-0.15.4-py2.py3-none-any.whl.metadata (4.5 kB)\n",
      "Requirement already satisfied: dask-expr<1.2,>=1.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask[array,dataframe]>=2.4.0->dask-ml) (1.1.13)\n",
      "Requirement already satisfied: jinja2>=2.10.3 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (3.1.4)\n",
      "Requirement already satisfied: locket>=1.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (1.0.0)\n",
      "Requirement already satisfied: msgpack>=1.0.2 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (1.0.3)\n",
      "Requirement already satisfied: psutil>=5.8.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (5.9.0)\n",
      "Requirement already satisfied: sortedcontainers>=2.0.5 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (2.4.0)\n",
      "Requirement already satisfied: tblib>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (1.7.0)\n",
      "Requirement already satisfied: tornado>=6.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (6.4.1)\n",
      "Requirement already satisfied: urllib3>=1.26.5 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (2.2.3)\n",
      "Requirement already satisfied: zict>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml) (3.0.0)\n",
      "Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from multipledispatch>=0.4.9->dask-ml) (1.16.0)\n",
      "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/anaconda3/lib/python3.12/site-packages (from numba>=0.51.0->dask-ml) (0.43.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml) (2023.3)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.2.0->dask-ml) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.2.0->dask-ml) (3.5.0)\n",
      "Requirement already satisfied: pyarrow>=14.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask-expr<1.2,>=1.1->dask[array,dataframe]>=2.4.0->dask-ml) (16.1.0)\n",
      "Requirement already satisfied: MarkupSafe>=2.0 in /opt/anaconda3/lib/python3.12/site-packages (from jinja2>=2.10.3->distributed>=2.4.0->dask-ml) (2.1.3)\n",
      "Downloading dask_ml-2024.4.4-py3-none-any.whl (149 kB)\n",
      "Downloading dask_glm-0.3.2-py2.py3-none-any.whl (13 kB)\n",
      "Downloading sparse-0.15.4-py2.py3-none-any.whl (237 kB)\n",
      "Installing collected packages: sparse, dask-glm, dask-ml\n",
      "Successfully installed dask-glm-0.3.2 dask-ml-2024.4.4 sparse-0.15.4\n",
      "Note: you may need to restart the kernel to use updated packages.\n",
      "Collecting dask-lightgbm\n",
      "  Using cached dask_lightgbm-0.2.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "Collecting dask<3.0.0,>=2.6.0 (from dask-lightgbm)\n",
      "  Downloading dask-2.30.0-py3-none-any.whl.metadata (3.4 kB)\n",
      "Collecting distributed<3.0.0,>=2.6.0 (from dask-lightgbm)\n",
      "  Downloading distributed-2.30.1-py3-none-any.whl.metadata (2.6 kB)\n",
      "Collecting lightgbm<3.0.0,>=2.3.0 (from dask-lightgbm)\n",
      "  Downloading lightgbm-2.3.1.tar.gz (679 kB)\n",
      "\u001b[2K     \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m679.3/679.3 kB\u001b[0m \u001b[31m17.0 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25h  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: numpy<2.0.0,>=1.17.3 in /opt/anaconda3/lib/python3.12/site-packages (from dask-lightgbm) (1.26.4)\n",
      "Collecting toolz<0.11.0,>=0.10.0 (from dask-lightgbm)\n",
      "  Downloading toolz-0.10.0.tar.gz (49 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hRequirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.12/site-packages (from dask<3.0.0,>=2.6.0->dask-lightgbm) (6.0.1)\n",
      "Requirement already satisfied: click>=6.6 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (8.1.7)\n",
      "Requirement already satisfied: cloudpickle>=1.5.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (3.0.0)\n",
      "Requirement already satisfied: msgpack>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (1.0.3)\n",
      "Requirement already satisfied: psutil>=5.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (5.9.0)\n",
      "Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (2.4.0)\n",
      "Requirement already satisfied: tblib>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (1.7.0)\n",
      "Requirement already satisfied: zict>=0.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (3.0.0)\n",
      "Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (75.1.0)\n",
      "Requirement already satisfied: tornado>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from distributed<3.0.0,>=2.6.0->dask-lightgbm) (6.4.1)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from lightgbm<3.0.0,>=2.3.0->dask-lightgbm) (1.13.1)\n",
      "Requirement already satisfied: scikit-learn in /opt/anaconda3/lib/python3.12/site-packages (from lightgbm<3.0.0,>=2.3.0->dask-lightgbm) (1.5.1)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->lightgbm<3.0.0,>=2.3.0->dask-lightgbm) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn->lightgbm<3.0.0,>=2.3.0->dask-lightgbm) (3.5.0)\n",
      "Downloading dask_lightgbm-0.2.0-py3-none-any.whl (5.8 kB)\n",
      "Downloading dask-2.30.0-py3-none-any.whl (848 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m848.4/848.4 kB\u001b[0m \u001b[31m29.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hDownloading distributed-2.30.1-py3-none-any.whl (656 kB)\n",
      "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m657.0/657.0 kB\u001b[0m \u001b[31m20.4 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
      "\u001b[?25hBuilding wheels for collected packages: lightgbm, toolz\n",
      "  Building wheel for lightgbm (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[102 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m INFO:root:running bdist_wheel\n",
      "  \u001b[31m   \u001b[0m INFO:root:running build\n",
      "  \u001b[31m   \u001b[0m INFO:root:running build_py\n",
      "  \u001b[31m   \u001b[0m INFO:root:creating build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/callback.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/compat.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/plotting.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/__init__.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/engine.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/basic.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/libpath.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/sklearn.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:running egg_info\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing lightgbm.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing dependency_links to lightgbm.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing requirements to lightgbm.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing top-level names to lightgbm.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:reading manifest file 'lightgbm.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m INFO:root:reading manifest template 'MANIFEST.in'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:no previously-included directories found matching 'build'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.so' under directory 'lightgbm'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.so' under directory 'compile'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.dll' under directory 'compile/Release'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no previously-included files matching '*.py[co]' found anywhere in distribution\n",
      "  \u001b[31m   \u001b[0m INFO:root:adding license file 'LICENSE'\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing manifest file 'lightgbm.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/VERSION.txt -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py:239: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         Please avoid running ``setup.py`` directly.\n",
      "  \u001b[31m   \u001b[0m         Instead, use pypa/build, pypa/installer or other\n",
      "  \u001b[31m   \u001b[0m         standards-based tools.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   install.initialize_options(self)\n",
      "  \u001b[31m   \u001b[0m INFO:root:installing to build/bdist.macosx-11.1-arm64/wheel\n",
      "  \u001b[31m   \u001b[0m INFO:root:running install\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile the library.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with CMake.\n",
      "  \u001b[31m   \u001b[0m WARNING:LightGBM:Compilation failed.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with Homebrew OpenMP paths guesses.\n",
      "  \u001b[31m   \u001b[0m WARNING:LightGBM:Compilation failed.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with MacPorts OpenMP paths guesses.\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py\", line 76, in silent_call\n",
      "  \u001b[31m   \u001b[0m     output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)\n",
      "  \u001b[31m   \u001b[0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 466, in check_output\n",
      "  \u001b[31m   \u001b[0m     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 548, in run\n",
      "  \u001b[31m   \u001b[0m     with Popen(*popenargs, **kwargs) as process:\n",
      "  \u001b[31m   \u001b[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 1026, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'cmake'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py\", line 310, in <module>\n",
      "  \u001b[31m   \u001b[0m     setup(name='lightgbm',\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/__init__.py\", line 117, in setup\n",
      "  \u001b[31m   \u001b[0m     return distutils.core.setup(**attrs)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/core.py\", line 183, in setup\n",
      "  \u001b[31m   \u001b[0m     return run_commands(dist)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/core.py\", line 199, in run_commands\n",
      "  \u001b[31m   \u001b[0m     dist.run_commands()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 954, in run_commands\n",
      "  \u001b[31m   \u001b[0m     self.run_command(cmd)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/dist.py\", line 950, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 973, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py\", line 433, in run\n",
      "  \u001b[31m   \u001b[0m     self.run_command(\"install\")\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/cmd.py\", line 316, in run_command\n",
      "  \u001b[31m   \u001b[0m     self.distribution.run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/dist.py\", line 950, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 973, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py\", line 267, in run\n",
      "  \u001b[31m   \u001b[0m     compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_mpi=self.mpi,\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py\", line 195, in compile_cpp\n",
      "  \u001b[31m   \u001b[0m     silent_call(cmake_cmd + get_cmake_opts('/opt/local/include/libomp',\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-o68pzyrb/lightgbm_cec634e49d95486eac4f2285b69d84c2/setup.py\", line 85, in silent_call\n",
      "  \u001b[31m   \u001b[0m     raise Exception(\"\\n\".join((error_msg, LOG_NOTICE)))\n",
      "  \u001b[31m   \u001b[0m Exception: Please install CMake and all required dependencies first\n",
      "  \u001b[31m   \u001b[0m The full version of error log was saved into /Users/abhinavsivanandhan/LightGBM_compilation.log\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for lightgbm\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for lightgbm\n",
      "  Building wheel for toolz (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for toolz: filename=toolz-0.10.0-py3-none-any.whl size=55568 sha256=9b5eccf501ccac84425a3bc263f61fd632dfe97e181416dabf1d587e59a51c05\n",
      "  Stored in directory: /Users/abhinavsivanandhan/Library/Caches/pip/wheels/02/f4/d6/211d2546fb8e699958ff029c0b397e8368dc2c3b17e97d5b20\n",
      "Successfully built toolz\n",
      "Failed to build lightgbm\n",
      "\u001b[31mERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lightgbm)\u001b[0m\u001b[31m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install dask-ml\n",
    "%pip install dask-lightgbm"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "f5a7e3bc-e5a7-4f01-9b23-dcb1d1606b69",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: dask-ml in /opt/anaconda3/lib/python3.12/site-packages (2024.4.4)\n",
      "Collecting dask-lightgbm\n",
      "  Using cached dask_lightgbm-0.2.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: matplotlib in /opt/anaconda3/lib/python3.12/site-packages (3.9.2)\n",
      "Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.12/site-packages (2.2.2)\n",
      "Requirement already satisfied: dask[complete] in /opt/anaconda3/lib/python3.12/site-packages (2024.8.2)\n",
      "Requirement already satisfied: click>=8.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (8.1.7)\n",
      "Requirement already satisfied: cloudpickle>=3.0.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (3.0.0)\n",
      "Requirement already satisfied: fsspec>=2021.09.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (2024.6.1)\n",
      "Requirement already satisfied: packaging>=20.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (24.1)\n",
      "Requirement already satisfied: partd>=1.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (1.4.1)\n",
      "Requirement already satisfied: pyyaml>=5.3.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (6.0.1)\n",
      "Requirement already satisfied: toolz>=0.10.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (0.12.0)\n",
      "Requirement already satisfied: pyarrow>=14.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (16.1.0)\n",
      "Requirement already satisfied: lz4>=4.3.2 in /opt/anaconda3/lib/python3.12/site-packages (from dask[complete]) (4.3.2)\n",
      "Requirement already satisfied: dask-glm>=0.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (0.3.2)\n",
      "Requirement already satisfied: distributed>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (2024.8.2)\n",
      "Requirement already satisfied: multipledispatch>=0.4.9 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (0.6.0)\n",
      "Requirement already satisfied: numba>=0.51.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (0.60.0)\n",
      "Requirement already satisfied: numpy>=1.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.26.4)\n",
      "Requirement already satisfied: scikit-learn>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.5.1)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.13.1)\n",
      "INFO: pip is looking at multiple versions of dask-lightgbm to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached dask_lightgbm-0.1.0-py3-none-any.whl.metadata (2.4 kB)\n",
      "Collecting dask-ml\n",
      "  Using cached dask_ml-2024.4.4-py3-none-any.whl.metadata (5.9 kB)\n",
      "  Using cached dask_ml-2024.3.20-py3-none-any.whl.metadata (4.3 kB)\n",
      "  Using cached dask_ml-2023.3.24-py3-none-any.whl.metadata (4.3 kB)\n",
      "INFO: pip is still looking at multiple versions of dask-lightgbm to determine which version is compatible with other requirements. This could take a while.\n",
      "  Using cached dask_ml-2022.5.27-py3-none-any.whl.metadata (4.3 kB)\n",
      "  Using cached dask_ml-2022.1.22-py3-none-any.whl.metadata (4.3 kB)\n",
      "  Using cached dask_ml-2021.11.30-py3-none-any.whl.metadata (4.3 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Using cached dask_ml-2021.11.16-py3-none-any.whl.metadata (4.3 kB)\n",
      "  Using cached dask_ml-2021.10.17-py3-none-any.whl.metadata (4.3 kB)\n",
      "  Using cached dask_ml-1.9.0-py3-none-any.whl.metadata (4.2 kB)\n",
      "  Using cached dask_ml-1.8.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "  Using cached dask_ml-1.7.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "  Using cached dask_ml-1.6.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "  Using cached dask_ml-1.5.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "  Using cached dask_ml-1.4.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "  Using cached dask_ml-1.3.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-1.2.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-1.1.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-1.1.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-1.0.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-0.13.0-py2.py3-none-any.whl.metadata (3.1 kB)\n",
      "Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml) (1.16.0)\n",
      "  Using cached dask_ml-0.12.0-py2.py3-none-any.whl.metadata (3.0 kB)\n",
      "  Using cached dask_ml-0.11.0-py2.py3-none-any.whl.metadata (2.8 kB)\n",
      "  Using cached dask_ml-0.10.0-py2.py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask_ml-0.9.0-py2.py3-none-any.whl.metadata (2.9 kB)\n",
      "  Using cached dask-ml-0.8.0.tar.gz (243 kB)\n",
      "  Installing build dependencies ... \u001b[?25ldone\n",
      "\u001b[?25h  Getting requirements to build wheel ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[20 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 353, in <module>\n",
      "  \u001b[31m   \u001b[0m     main()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 335, in main\n",
      "  \u001b[31m   \u001b[0m     json_out['return_val'] = hook(**hook_input['kwargs'])\n",
      "  \u001b[31m   \u001b[0m                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py\", line 118, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return hook(config_settings)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-build-env-o8yq824h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py\", line 334, in get_requires_for_build_wheel\n",
      "  \u001b[31m   \u001b[0m     return self._get_build_requires(config_settings, requirements=[])\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-build-env-o8yq824h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py\", line 304, in _get_build_requires\n",
      "  \u001b[31m   \u001b[0m     self.run_setup()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-build-env-o8yq824h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py\", line 522, in run_setup\n",
      "  \u001b[31m   \u001b[0m     super().run_setup(setup_script=setup_script)\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-build-env-o8yq824h/overlay/lib/python3.12/site-packages/setuptools/build_meta.py\", line 320, in run_setup\n",
      "  \u001b[31m   \u001b[0m     exec(code, locals())\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 4, in <module>\n",
      "  \u001b[31m   \u001b[0m ModuleNotFoundError: No module named 'numpy'\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "\n",
      "\u001b[31m×\u001b[0m \u001b[32mGetting requirements to build wheel\u001b[0m did not run successfully.\n",
      "\u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "\u001b[31m╰─>\u001b[0m See above for output.\n",
      "\n",
      "\u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[?25hNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install \"dask[complete]\" dask-ml dask-lightgbm matplotlib pandas\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "ac8af63b-e8c5-45a6-9579-d24a32978fe0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: dask-ml>=2024.1 in /opt/anaconda3/lib/python3.12/site-packages (2024.4.4)\n",
      "Collecting dask-lightgbm>=0.2.0\n",
      "  Using cached dask_lightgbm-0.2.0-py3-none-any.whl.metadata (2.7 kB)\n",
      "Requirement already satisfied: dask-glm>=0.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (0.3.2)\n",
      "Requirement already satisfied: dask>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[array,dataframe]>=2.4.0->dask-ml>=2024.1) (2024.8.2)\n",
      "Requirement already satisfied: distributed>=2.4.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (2024.8.2)\n",
      "Requirement already satisfied: multipledispatch>=0.4.9 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (0.6.0)\n",
      "Requirement already satisfied: numba>=0.51.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (0.60.0)\n",
      "Requirement already satisfied: numpy>=1.20.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (1.26.4)\n",
      "Requirement already satisfied: packaging in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (24.1)\n",
      "Requirement already satisfied: pandas>=0.24.2 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (2.2.2)\n",
      "Requirement already satisfied: scikit-learn>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (1.5.1)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.12/site-packages (from dask-ml>=2024.1) (1.13.1)\n",
      "Collecting dask>=2.4.0 (from dask[array,dataframe]>=2.4.0->dask-ml>=2024.1)\n",
      "  Using cached dask-2.30.0-py3-none-any.whl.metadata (3.4 kB)\n",
      "Collecting distributed>=2.4.0 (from dask-ml>=2024.1)\n",
      "  Using cached distributed-2.30.1-py3-none-any.whl.metadata (2.6 kB)\n",
      "Collecting lightgbm<3.0.0,>=2.3.0 (from dask-lightgbm>=0.2.0)\n",
      "  Using cached lightgbm-2.3.1.tar.gz (679 kB)\n",
      "  Preparing metadata (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25hCollecting toolz<0.11.0,>=0.10.0 (from dask-lightgbm>=0.2.0)\n",
      "  Using cached toolz-0.10.0-py3-none-any.whl\n",
      "Requirement already satisfied: pyyaml in /opt/anaconda3/lib/python3.12/site-packages (from dask>=2.4.0->dask[array,dataframe]>=2.4.0->dask-ml>=2024.1) (6.0.1)\n",
      "Requirement already satisfied: cloudpickle>=0.2.2 in /opt/anaconda3/lib/python3.12/site-packages (from dask-glm>=0.2.0->dask-ml>=2024.1) (3.0.0)\n",
      "Requirement already satisfied: sparse>=0.7.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask-glm>=0.2.0->dask-ml>=2024.1) (0.15.4)\n",
      "INFO: pip is looking at multiple versions of dask[array,dataframe] to determine which version is compatible with other requirements. This could take a while.\n",
      "Collecting dask[array,dataframe]>=2.4.0 (from dask-ml>=2024.1)\n",
      "  Downloading dask-2024.12.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Using cached dask-2024.11.2-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.11.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.10.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.9.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.9.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.8.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "INFO: pip is still looking at multiple versions of dask[array,dataframe] to determine which version is compatible with other requirements. This could take a while.\n",
      "  Downloading dask-2024.8.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.7.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.7.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.6.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.6.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.\n",
      "  Downloading dask-2024.6.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.5.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.5.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.5.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.4.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.4.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.4.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.3.1-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.3.0-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2024.2.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.2.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.1.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2024.1.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.12.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.12.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.11.0-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.10.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.10.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.9.3-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.9.2-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.9.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.9.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.8.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.8.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.7.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.7.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.6.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.6.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.5.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.5.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.4.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.4.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.3.2-py3-none-any.whl.metadata (3.8 kB)\n",
      "  Downloading dask-2023.3.1-py3-none-any.whl.metadata (3.7 kB)\n",
      "  Downloading dask-2023.3.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.2.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.2.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.1.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2023.1.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.12.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.12.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.11.1-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.11.0-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.10.2-py3-none-any.whl.metadata (3.6 kB)\n",
      "  Downloading dask-2022.10.0-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.9.2-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.9.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.9.0-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.8.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.8.0-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.7.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.7.0-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.6.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.6.0-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.5.2-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.5.1-py3-none-any.whl.metadata (3.5 kB)\n",
      "  Downloading dask-2022.5.0-py3-none-any.whl.metadata (3.4 kB)\n",
      "  Downloading dask-2022.4.2-py3-none-any.whl.metadata (3.4 kB)\n",
      "  Downloading dask-2022.4.1-py3-none-any.whl.metadata (3.4 kB)\n",
      "  Downloading dask-2022.4.0-py3-none-any.whl.metadata (3.4 kB)\n",
      "  Downloading dask-2022.3.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2022.2.1-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2022.2.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2022.1.1-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2022.1.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.12.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.11.2-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.11.1-py3-none-any.whl.metadata (3.1 kB)\n",
      "  Downloading dask-2021.11.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.10.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.9.1-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.9.0-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.8.1-py3-none-any.whl.metadata (3.0 kB)\n",
      "  Downloading dask-2021.8.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.7.2-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.7.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.7.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.6.2-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.6.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.6.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.5.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.5.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.4.1-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.4.0-py3-none-any.whl.metadata (2.9 kB)\n",
      "  Downloading dask-2021.3.1-py3-none-any.whl.metadata (2.8 kB)\n",
      "  Downloading dask-2021.3.0-py3-none-any.whl.metadata (3.3 kB)\n",
      "  Downloading dask-2021.2.0-py3-none-any.whl.metadata (3.3 kB)\n",
      "  Downloading dask-2021.1.1-py3-none-any.whl.metadata (3.3 kB)\n",
      "  Downloading dask-2021.1.0-py3-none-any.whl.metadata (3.3 kB)\n",
      "  Downloading dask-2020.12.0-py3-none-any.whl.metadata (3.3 kB)\n",
      "Requirement already satisfied: partd>=0.3.10 in /opt/anaconda3/lib/python3.12/site-packages (from dask[array,dataframe]>=2.4.0->dask-ml>=2024.1) (1.4.1)\n",
      "Requirement already satisfied: fsspec>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from dask[array,dataframe]>=2.4.0->dask-ml>=2024.1) (2024.6.1)\n",
      "Requirement already satisfied: click>=6.6 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (8.1.7)\n",
      "Requirement already satisfied: msgpack>=0.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (1.0.3)\n",
      "Requirement already satisfied: psutil>=5.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (5.9.0)\n",
      "Requirement already satisfied: sortedcontainers!=2.0.0,!=2.0.1 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (2.4.0)\n",
      "Requirement already satisfied: tblib>=1.6.0 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (1.7.0)\n",
      "Requirement already satisfied: zict>=0.1.3 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (3.0.0)\n",
      "Requirement already satisfied: setuptools in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (75.1.0)\n",
      "Requirement already satisfied: tornado>=6.0.3 in /opt/anaconda3/lib/python3.12/site-packages (from distributed>=2.4.0->dask-ml>=2024.1) (6.4.1)\n",
      "Requirement already satisfied: six in /opt/anaconda3/lib/python3.12/site-packages (from multipledispatch>=0.4.9->dask-ml>=2024.1) (1.16.0)\n",
      "Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /opt/anaconda3/lib/python3.12/site-packages (from numba>=0.51.0->dask-ml>=2024.1) (0.43.0)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml>=2024.1) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml>=2024.1) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.12/site-packages (from pandas>=0.24.2->dask-ml>=2024.1) (2023.3)\n",
      "Requirement already satisfied: joblib>=1.2.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.2.0->dask-ml>=2024.1) (1.4.2)\n",
      "Requirement already satisfied: threadpoolctl>=3.1.0 in /opt/anaconda3/lib/python3.12/site-packages (from scikit-learn>=1.2.0->dask-ml>=2024.1) (3.5.0)\n",
      "Requirement already satisfied: locket in /opt/anaconda3/lib/python3.12/site-packages (from partd>=0.3.10->dask[array,dataframe]>=2.4.0->dask-ml>=2024.1) (1.0.0)\n",
      "Using cached dask_lightgbm-0.2.0-py3-none-any.whl (5.8 kB)\n",
      "Using cached dask-2.30.0-py3-none-any.whl (848 kB)\n",
      "Using cached distributed-2.30.1-py3-none-any.whl (656 kB)\n",
      "Building wheels for collected packages: lightgbm\n",
      "  Building wheel for lightgbm (setup.py) ... \u001b[?25lerror\n",
      "  \u001b[1;31merror\u001b[0m: \u001b[1msubprocess-exited-with-error\u001b[0m\n",
      "  \n",
      "  \u001b[31m×\u001b[0m \u001b[32mpython setup.py bdist_wheel\u001b[0m did not run successfully.\n",
      "  \u001b[31m│\u001b[0m exit code: \u001b[1;36m1\u001b[0m\n",
      "  \u001b[31m╰─>\u001b[0m \u001b[31m[102 lines of output]\u001b[0m\n",
      "  \u001b[31m   \u001b[0m INFO:root:running bdist_wheel\n",
      "  \u001b[31m   \u001b[0m INFO:root:running build\n",
      "  \u001b[31m   \u001b[0m INFO:root:running build_py\n",
      "  \u001b[31m   \u001b[0m INFO:root:creating build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/callback.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/compat.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/plotting.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/__init__.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/engine.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/basic.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/libpath.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/sklearn.py -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m INFO:root:running egg_info\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing lightgbm.egg-info/PKG-INFO\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing dependency_links to lightgbm.egg-info/dependency_links.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing requirements to lightgbm.egg-info/requires.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing top-level names to lightgbm.egg-info/top_level.txt\n",
      "  \u001b[31m   \u001b[0m INFO:root:reading manifest file 'lightgbm.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m INFO:root:reading manifest template 'MANIFEST.in'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:no previously-included directories found matching 'build'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.so' under directory 'lightgbm'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.so' under directory 'compile'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.dll' under directory 'compile/Release'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no files found matching '*.dll' under directory 'compile/windows/x64/DLL'\n",
      "  \u001b[31m   \u001b[0m WARNING:root:warning: no previously-included files matching '*.py[co]' found anywhere in distribution\n",
      "  \u001b[31m   \u001b[0m INFO:root:adding license file 'LICENSE'\n",
      "  \u001b[31m   \u001b[0m INFO:root:writing manifest file 'lightgbm.egg-info/SOURCES.txt'\n",
      "  \u001b[31m   \u001b[0m INFO:root:copying lightgbm/VERSION.txt -> build/lib/lightgbm\n",
      "  \u001b[31m   \u001b[0m /private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py:239: SetuptoolsDeprecationWarning: setup.py install is deprecated.\n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m         Please avoid running ``setup.py`` directly.\n",
      "  \u001b[31m   \u001b[0m         Instead, use pypa/build, pypa/installer or other\n",
      "  \u001b[31m   \u001b[0m         standards-based tools.\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m         See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.\n",
      "  \u001b[31m   \u001b[0m         ********************************************************************************\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m !!\n",
      "  \u001b[31m   \u001b[0m   install.initialize_options(self)\n",
      "  \u001b[31m   \u001b[0m INFO:root:installing to build/bdist.macosx-11.1-arm64/wheel\n",
      "  \u001b[31m   \u001b[0m INFO:root:running install\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile the library.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with CMake.\n",
      "  \u001b[31m   \u001b[0m WARNING:LightGBM:Compilation failed.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with Homebrew OpenMP paths guesses.\n",
      "  \u001b[31m   \u001b[0m WARNING:LightGBM:Compilation failed.\n",
      "  \u001b[31m   \u001b[0m INFO:LightGBM:Starting to compile with MacPorts OpenMP paths guesses.\n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py\", line 76, in silent_call\n",
      "  \u001b[31m   \u001b[0m     output = subprocess.check_output(cmd, stderr=subprocess.STDOUT)\n",
      "  \u001b[31m   \u001b[0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 466, in check_output\n",
      "  \u001b[31m   \u001b[0m     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 548, in run\n",
      "  \u001b[31m   \u001b[0m     with Popen(*popenargs, **kwargs) as process:\n",
      "  \u001b[31m   \u001b[0m          ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 1026, in __init__\n",
      "  \u001b[31m   \u001b[0m     self._execute_child(args, executable, preexec_fn, close_fds,\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/subprocess.py\", line 1955, in _execute_child\n",
      "  \u001b[31m   \u001b[0m     raise child_exception_type(errno_num, err_msg, err_filename)\n",
      "  \u001b[31m   \u001b[0m FileNotFoundError: [Errno 2] No such file or directory: 'cmake'\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m During handling of the above exception, another exception occurred:\n",
      "  \u001b[31m   \u001b[0m \n",
      "  \u001b[31m   \u001b[0m Traceback (most recent call last):\n",
      "  \u001b[31m   \u001b[0m   File \"<string>\", line 2, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"<pip-setuptools-caller>\", line 34, in <module>\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py\", line 310, in <module>\n",
      "  \u001b[31m   \u001b[0m     setup(name='lightgbm',\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/__init__.py\", line 117, in setup\n",
      "  \u001b[31m   \u001b[0m     return distutils.core.setup(**attrs)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/core.py\", line 183, in setup\n",
      "  \u001b[31m   \u001b[0m     return run_commands(dist)\n",
      "  \u001b[31m   \u001b[0m            ^^^^^^^^^^^^^^^^^^\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/core.py\", line 199, in run_commands\n",
      "  \u001b[31m   \u001b[0m     dist.run_commands()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 954, in run_commands\n",
      "  \u001b[31m   \u001b[0m     self.run_command(cmd)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/dist.py\", line 950, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 973, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/command/bdist_wheel.py\", line 433, in run\n",
      "  \u001b[31m   \u001b[0m     self.run_command(\"install\")\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/cmd.py\", line 316, in run_command\n",
      "  \u001b[31m   \u001b[0m     self.distribution.run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/dist.py\", line 950, in run_command\n",
      "  \u001b[31m   \u001b[0m     super().run_command(command)\n",
      "  \u001b[31m   \u001b[0m   File \"/opt/anaconda3/lib/python3.12/site-packages/setuptools/_distutils/dist.py\", line 973, in run_command\n",
      "  \u001b[31m   \u001b[0m     cmd_obj.run()\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py\", line 267, in run\n",
      "  \u001b[31m   \u001b[0m     compile_cpp(use_mingw=self.mingw, use_gpu=self.gpu, use_mpi=self.mpi,\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py\", line 195, in compile_cpp\n",
      "  \u001b[31m   \u001b[0m     silent_call(cmake_cmd + get_cmake_opts('/opt/local/include/libomp',\n",
      "  \u001b[31m   \u001b[0m   File \"/private/var/folders/1s/991tybk51zndg1yc51wjq1v80000gn/T/pip-install-67fi8neh/lightgbm_fd1c4f5e040b424f99984257a4fbc97d/setup.py\", line 85, in silent_call\n",
      "  \u001b[31m   \u001b[0m     raise Exception(\"\\n\".join((error_msg, LOG_NOTICE)))\n",
      "  \u001b[31m   \u001b[0m Exception: Please install CMake and all required dependencies first\n",
      "  \u001b[31m   \u001b[0m The full version of error log was saved into /Users/abhinavsivanandhan/LightGBM_compilation.log\n",
      "  \u001b[31m   \u001b[0m \u001b[31m[end of output]\u001b[0m\n",
      "  \n",
      "  \u001b[1;35mnote\u001b[0m: This error originates from a subprocess, and is likely not a problem with pip.\n",
      "\u001b[31m  ERROR: Failed building wheel for lightgbm\u001b[0m\u001b[31m\n",
      "\u001b[0m\u001b[?25h  Running setup.py clean for lightgbm\n",
      "Failed to build lightgbm\n",
      "\u001b[31mERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (lightgbm)\u001b[0m\u001b[31m\n",
      "\u001b[0mNote: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "%pip install \"dask-ml>=2024.1\" \"dask-lightgbm>=0.2.0\"\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a1550ef2-7172-437d-80e9-fec6077be91f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
